### ISSUE TITLE
Set default `podSecurity` context for Gotenberg

### ISSUE THREAD

**Issue by MaikuMori** [MaikuMori/helm-charts#23]
The official documentation recommends:

```yaml
securityContext:
  privileged: false
  runAsUser: 1001
```

I'm thinking about adding this as default moving forwards. A somewhat breaking change.
