### ISSUE TITLE
Probes fail when Basic Auth is enabled

### ISSUE THREAD

**Issue by wegerts** [MaikuMori/helm-charts#37]
First thank you for providing and maintaining this chart! :-)

Just found after enabling basic auth the probes fail due to 401 responses.
Can be easily fixed by adding an httpHeader to the probes as follows:
```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic <base64: user:password>
            path: /health
            ...
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Authorization
              value: Basic <base64: user:password>
            path: /health
            ...
```
